fos_user:
    db_driver: orm
    firewall_name: main
    user_class: FFN\MonBundle\Entity\User
    registration:
        confirmation:
            enabled:    true

services:
    ffn_kernel_listener_locale:
        class: FFN\MonBundle\Listener\FFNRequestListener
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments:
          - "@service_container"
          