parameters:
  weather_default_dns_threshold: 1.0
  weather_default_tcp_threshold: 1.5
  weather_default_first_packet_threshold: 3.0
  weather_default_total_time_threshold: 5.0
  weather_default_window_size: 5
  weather_default_valid_codes: [200, 301, 302]
  weather_very_good_score: 1150
  weather_average_score: 1100
  weather_poor_score: 1050
  weather_bad_score: 0150
  nb_users: 3
  nb_projects: 4
  nb_scenarios: 3
  nb_controls: 3

twig:
  globals:
    nb_max_list: 3
    max_project_description_length: 94
    max_scenario_name_list_length: 39
    max_scenario_name_title_length: 27
    max_control_name_list_length: 39
    max_control_name_title_length: 27