mon_admin_user_add:
    pattern:  /admin/user/add
    defaults: { _controller: FFNMonBundle:Default:adminUserAdd}
    requirements:
        _method: GET|POST

mon_admin_user_activation:
    pattern: /admin/user/active/{id}/{statut}
    defaults: { _controller: FFNMonBundle:Default:adminUserActivation}
    requirements:
        _method: GET|POST
        statut: true|false
        
mon_admin_user_delete:
    pattern:  /admin/user/delete/{id}
    defaults: { _controller: FFNMonBundle:Default:adminUserDelete}
    requirements:
        _method: GET
        id: \d+
        
mon_admin_user_edit:
    pattern:  /admin/user/{id}
    defaults: { _controller: FFNMonBundle:Default:adminUserEdit}
    requirements:
        _method: GET
        id: \d+

mon_admin_user:
    pattern:  /admin/user
    defaults: { _controller: FFNMonBundle:Default:adminUser}
    requirements:
        _method: GET

mon_project_add: 
    pattern: /project/add
    defaults: { _controller: FFNMonBundle:Default:projectAdd}
    requirements:
        _method: GET|POST
        
mon_project_home: 
    pattern: /project/{id}
    defaults: { _controller: FFNMonBundle:Default:project}
    requirements:
        _method: GET|POST
        id: \d+

mon_scenario_add:
    pattern: /scenario/add/{id}
    defaults: { _controller: FFNMonBundle:Default:scenarioAdd}
    requirements:
        _method: GET|POST
        id: \d+

mon_scenario_edit:
    pattern: /scenario/edit/{id}
    defaults: { _controller: FFNMonBundle:Default:scenarioEdit}
    requirements:
        _method: GET|POST
        id: \d+

mon_scenario_delete:
    pattern: /scenario/delete/{id}
    defaults: { _controller: FFNMonBundle:Default:scenarioDelete}
    requirements:
        _method: GET
        id: \d+
        
mon_control_add:
    pattern: /control/add/{id}
    defaults: { _controller: FFNMonBundle:Default:controlAdd}
    requirements:
        _method: GET|POST
        id: \d+
        
mon_home:
    pattern:  /
    defaults: { _controller: FFNMonBundle:Default:home}
    requirements:
        _method: GET
        
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
