mon_home:
    pattern:  /
    defaults: { _controller: FFNMonBundle:Default:home }
    requirements:
        _method: GET

mon_about:
  pattern: /{_locale}/about
  defaults:
    _controller: FFNMonBundle:About:show
    _locale: %locale%
    maxAge: 86400
    sharedMaxAge: 86400
    private: false
  requirements:
    _locale: en|fr

mon_faq:
  pattern: /{_locale}/faq
  defaults:
    _controller: FFNMonBundle:FAQ:show
    _locale: %locale%
    maxAge: 86400
    sharedMaxAge: 86400
    private: false
  requirements:
    _locale: en|fr

mon_contact:
  pattern: /{_locale}/contact
  defaults:
    _controller: FFNMonBundle:Contact:show
    _locale: %locale%
    maxAge: 86400
    sharedMaxAge: 86400
    private: false
  requirements:
    _locale: en|fr

mon_graph:
  pattern: /{_locale}/graph/{control_id}/{startTs}/{stopTs}
  defaults:
    _controller: FFNMonBundle:Graph:show
  requirements:
    _locale: en|fr
    control_id: \d+
    startTs: \d\d\d\d\-\d\d\-\d\d\s\d\d:\d\d:\d\d
    stopTs: \d\d\d\d\-\d\d\-\d\d\s\d\d:\d\d:\d\d

mon_graph_simple:
  pattern: /{_locale}/graph/{control_id}
  defaults:
    _controller: FFNMonBundle:Graph:show
  requirements:
    _locale: en|fr
    control_id: \d+

# Admin
mon_admin_user_add:
    pattern:  /{_locale}/admin/user/add
    defaults:
      _controller: FFNMonBundle:User:adminUserAdd
      _locale: %locale%
    requirements:
        _method: GET|POST
        _locale: en|fr

mon_admin_user_activation:
    pattern: /{_locale}/admin/user/active/{id}/{statut}
    defaults: { _controller: FFNMonBundle:User:adminUserActivation }
    requirements:
        _method: GET|POST
        _locale: en|fr
        statut: true|false

mon_admin_user_delete:
    pattern:  /{_locale}/admin/user/delete/{id}
    defaults: { _controller: FFNMonBundle:User:adminUserDelete }
    requirements:
        _method: GET
        id: \d+

mon_admin_user_edit:
    pattern:  /{_locale}/admin/user/{id}
    defaults: { _controller: FFNMonBundle:User:adminUserEdit }
    requirements:
        _method: GET
        _locale: en|fr
        id: \d+

mon_admin_user:
    pattern:  /{_locale}/admin/user
    defaults: { _controller: FFNMonBundle:User:adminUser }
    requirements:
        _method: GET
        _locale: en|fr

# Projects
mon_project_add:
    pattern: /project/add
    defaults: { _controller: FFNMonBundle:Project:projectAdd }
    requirements:
        _method: GET|POST
        _locale: en|fr

mon_project_home:
    pattern: /project/{id}
    defaults: { _controller: FFNMonBundle:Project:project }
    requirements:
        _method: GET|POST
        id: \d+

mon_project_edit:
    pattern: /project/edit/{id}
    defaults: { _controller: FFNMonBundle:Project:projectEdit }
    requirements:
        _method: GET|POST

mon_project_delete:
    pattern: /project/delete/{id}
    defaults: { _controller: FFNMonBundle:Project:projectDelete }
    requirements:
        _method: GET
        id: \d+

mon_scenario_add:
    pattern: /scenario/add/{id}
    defaults: { _controller: FFNMonBundle:Scenario:scenarioAdd }
    requirements:
        _method: GET|POST
        id: \d+

mon_scenario_home:
    pattern: /scenario/{id}
    defaults: { _controller: FFNMonBundle:Scenario:scenario }
    requirements:
        _method: GET|POST
        id: \d+

mon_scenario_edit:
    pattern: /scenario/edit/{id}
    defaults: { _controller: FFNMonBundle:Scenario:scenarioEdit }
    requirements:
        _method: GET|POST
        id: \d+

mon_scenario_delete:
    pattern: /scenario/delete/{id}
    defaults: { _controller: FFNMonBundle:Scenario:scenarioDelete }
    requirements:
        _method: GET
        id: \d+

mon_control_add:
    pattern: /control/add/{id}
    defaults: { _controller: FFNMonBundle:Control:controlAdd }
    requirements:
        _method: GET|POST
        id: \d+

mon_control_edit:
    pattern: /control/edit/{id}
    defaults: { _controller: FFNMonBundle:Control:controlEdit }
    requirements:
        _method: GET|POST
        id: \d+

mon_control_delete:
    pattern: /control/delete/{id}
    defaults: { _controller: FFNMonBundle:Control:controlDelete }
    requirements:
        _method: GET|POST
        id: \d+
