imports:
    - { resource: security.yml }
    - { resource: "@FFNMonBundle/Resources/config/config.yml" }
    - { resource: "@FFNMonBundle/Resources/config/parameters.yml" }
    - { resource: "@FFNUserBundle/Resources/config/parameters.yml" }

framework:
    # esi:             ~
    translator:      { fallback: "undefined" }
    default_locale:  en
    secret: %secret%
    router:
      resource: "%kernel.root_dir%/config/routing.yml"
      strict_requirements: %kernel.debug%
    form: true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      
      engines: ['twig']
      assets_base_urls: 
        http: %http_site_urls%
        ssl: %https_site_urls%
      # assets_version: SomeVersionScheme
    session: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ FFNMonBundle ]
    java: %java_path%
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    delivery_address: %mailer_delivery_address%
    spool:     { type: memory }

# FOSUserBundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: FFN\UserBundle\Entity\User
    registration:
        confirmation:
            enabled:    true
    from_email:
        address: webofmars@gmail.com
        sender_name: WoM User Administrator (do not reply)
            
# Lunetics Locale Switcher
lunetics_locale:
  strict_mode: false
  allowed_locales:
    - fr
    - en
  guessing_order:
    - cookie
    - router
    - browser
  switcher:
    template: FFNMonBundle::localeSwitcher.html.twig
    show_current_locale: true
  cookie:
    set_on_change: true