parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: mon
    database_user: root
    database_password: ngooxav
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    mailer_delivery_address: null
    locale: fr
    secret: 278b98a07f1af43a9531895f6c8552fe3a16a8fd
    database_path: null
    your_gmail_username: fabien.somnier@buongiorno.com
    your_gmail_password:

