jms_security_extra:
    secure_all_services: false
    expressions: true

security:        
  encoders:
        FOS\UserBundle\Model\UserInterface: sha512
  role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
  providers:
    fos_userbundle:
      id: fos_user.user_provider.username
      
  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false
      
    main:
      pattern: ^/
      anonymous: true
      form_login:
        provider: fos_userbundle
        csrf_provider: form.csrf_provider
        login_path: fos_user_security_login
        check_path: fos_user_security_check
        failure_path: null
        always_use_default_target_path : true
        default_target_path: mon_home
        use_forward: true
      logout:
        path: fos_user_security_logout
        target: /
    public:
      pattern: ^/(fr|en)/(faq|about|contact)
      anonymous: true
    fos_user_bundle_fw:
      pattern: ^/(fr|en)/(login|resetting)
      anonymous: true

  access_control:
    - { path: ^/(fr|en)/login,          role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/(fr|en)/resetting,      role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/(fr|en)/about,          role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/(fr|en)/contact,        role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/(fr|en)/faq,            role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/(fr|en)/admin/user/add, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/(fr|en)/admin,          role: ROLE_ADMIN }
    - { path: ^/,                       role: IS_AUTHENTICATED_FULLY}