<?php

namespace FFN\MonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * capture_detailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class capture_detailRepository extends EntityRepository
{
}
