<?php

namespace FFN\MonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * control_headerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class control_headerRepository extends EntityRepository
{
}
