<?php

namespace FFN\MonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * scenarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class scenarioRepository extends EntityRepository
{
}
